version: '3'

services:
  karma-api:
    depends_on:
      - postgres
    links:
      - "postgres"
    build: ./server
    ports:
      - "8080:8080"
    environment:
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: 'app_user'
      PGPASSWORD: 'pleaseupdateme'
      PGHOST: "postgres"
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
